# Generated by Django 2.0 on 2018-07-24 21:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisBasis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosisbasis_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosisbasis_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'diagnosisbases',
                'db_table': 'whispers_diagnosisbasis',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosiscause_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosiscause_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whispers_diagnosiscause',
            },
        ),
        migrations.RemoveField(
            model_name='speciesdiagnosis',
            name='causal',
        ),
        migrations.RemoveField(
            model_name='speciesdiagnosis',
            name='major',
        ),
        migrations.AddField(
            model_name='speciesdiagnosis',
            name='diagnosis_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='speciesdiagnosis',
            name='basis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='speciesdiagnoses', to='whispersapi.DiagnosisBasis'),
        ),
        migrations.AddField(
            model_name='speciesdiagnosis',
            name='cause',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='speciesdiagnoses', to='whispersapi.DiagnosisCause'),
        ),
    ]
