# Generated by Django 2.0 on 2018-07-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0003_auto_20180725_1044'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventlocation',
            unique_together=set(),
        ),
    ]
