# Generated by Django 2.0 on 2018-07-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0004_auto_20180730_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
