# Generated by Django 2.0 on 2018-08-02 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0006_auto_20180802_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='whispersapi.EventStatus'),
        ),
        migrations.AlterField(
            model_name='event',
            name='legal_status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='whispersapi.LegalStatus'),
        ),
        migrations.AlterField(
            model_name='event',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='whispersapi.Staff'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='administrative_level_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventlocations', to='whispersapi.AdministrativeLevelTwo'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='land_ownership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventlocations', to='whispersapi.LandOwnership'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='administrative_level_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='whispersapi.AdministrativeLevelOne'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='whispersapi.Country'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
