# Generated by Django 2.0 on 2018-08-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0010_auto_20180820_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='laboratory',
            field=models.BooleanField(default=False),
        ),
    ]
