# Generated by Django 2.1 on 2018-10-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0012_auto_20180911_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdiagnosis',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='speciesdiagnosis',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='eventdiagnosis',
            name='suspect',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='speciesdiagnosis',
            name='suspect',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
