# Generated by Django 2.1 on 2018-10-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0013_auto_20181001_1331'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='speciesdiagnosis',
            unique_together={('location_species', 'diagnosis')},
        ),
        migrations.AlterUniqueTogether(
            name='speciesdiagnosisorganization',
            unique_together={('species_diagnosis', 'organization')},
        ),
    ]
