# Generated by Django 2.1 on 2018-10-11 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0017_specimensubmissionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimensubmissionrequest',
            name='request_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specimensubmissionrequests', to='whispersapi.SpecimenSubmissionRequestResponse'),
        ),
    ]
