# Generated by Django 2.1 on 2018-10-14 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0021_auto_20181012_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='created_time',
            field=models.TimeField(blank=True, default=datetime.time(22, 31, 21, 221366), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='eventdiagnosis',
            unique_together={('event', 'diagnosis')},
        ),
    ]
