# Generated by Django 2.1 on 2018-10-18 20:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0022_auto_20181013_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativelevellocality',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='administrativelevelone',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='administrativeleveltwo',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='agebias',
            options={'ordering': ['id'], 'verbose_name_plural': 'agebiases'},
        ),
        migrations.AlterModelOptions(
            name='artifact',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='circle',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='circleuser',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='commenttype',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contacttype',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['id'], 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ['id'], 'verbose_name_plural': 'diagnoses'},
        ),
        migrations.AlterModelOptions(
            name='diagnosisbasis',
            options={'ordering': ['id'], 'verbose_name_plural': 'diagnosisbases'},
        ),
        migrations.AlterModelOptions(
            name='diagnosiscause',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='diagnosistype',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='eventabstract',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='eventcase',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='eventcontact',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='eventdiagnosis',
            options={'ordering': ['event', 'priority'], 'verbose_name_plural': 'eventdiagnoses'},
        ),
        migrations.AlterModelOptions(
            name='eventlabsite',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='eventlocation',
            options={'ordering': ['event', 'priority']},
        ),
        migrations.AlterModelOptions(
            name='eventlocationcontact',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='eventlocationflyway',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='eventorganization',
            options={'ordering': ['event', 'priority']},
        ),
        migrations.AlterModelOptions(
            name='eventstatus',
            options={'ordering': ['id'], 'verbose_name_plural': 'eventstatuses'},
        ),
        migrations.AlterModelOptions(
            name='eventsuperevent',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='flyway',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='landownership',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='legalstatus',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='locationspecies',
            options={'ordering': ['event_location', 'priority'], 'verbose_name_plural': 'locationspecies'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['id'], 'verbose_name_plural': 'searches'},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='servicerequestresponse',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='servicerequesttype',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sexbias',
            options={'ordering': ['id'], 'verbose_name_plural': 'sexbiases'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['id'], 'verbose_name_plural': 'species'},
        ),
        migrations.AlterModelOptions(
            name='speciesdiagnosis',
            options={'ordering': ['location_species', 'priority'], 'verbose_name_plural': 'speciesdiagnoses'},
        ),
        migrations.AlterModelOptions(
            name='speciesdiagnosisorganization',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='superevent',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='administrativelevellocality',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='whispersapi.Country'),
        ),
        migrations.AlterField(
            model_name='administrativelevelone',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrativelevelones', to='whispersapi.Country'),
        ),
        migrations.AlterField(
            model_name='administrativeleveltwo',
            name='administrative_level_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrativeleveltwos', to='whispersapi.AdministrativeLevelOne'),
        ),
        migrations.AlterField(
            model_name='circleuser',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whispersapi.Circle'),
        ),
        migrations.AlterField(
            model_name='circleuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventabstract',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventabstracts', to='whispersapi.Event'),
        ),
        migrations.AlterField(
            model_name='eventcase',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventcases', to='whispersapi.Event'),
        ),
        migrations.AlterField(
            model_name='eventcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whispersapi.Contact'),
        ),
        migrations.AlterField(
            model_name='eventcontact',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whispersapi.Event'),
        ),
        migrations.AlterField(
            model_name='eventdiagnosis',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventdiagnoses', to='whispersapi.Event'),
        ),
        migrations.AlterField(
            model_name='eventlabsite',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventlabsites', to='whispersapi.Event'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventlocations', to='whispersapi.Event'),
        ),
        migrations.AlterField(
            model_name='eventlocationcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whispersapi.Contact'),
        ),
        migrations.AlterField(
            model_name='eventlocationcontact',
            name='event_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whispersapi.EventLocation'),
        ),
        migrations.AlterField(
            model_name='eventlocationflyway',
            name='event_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whispersapi.EventLocation'),
        ),
        migrations.AlterField(
            model_name='eventlocationflyway',
            name='flyway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whispersapi.Flyway'),
        ),
        migrations.AlterField(
            model_name='eventorganization',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whispersapi.Event'),
        ),
        migrations.AlterField(
            model_name='eventorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whispersapi.Organization'),
        ),
        migrations.AlterField(
            model_name='eventsuperevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whispersapi.Event'),
        ),
        migrations.AlterField(
            model_name='eventsuperevent',
            name='superevent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whispersapi.SuperEvent'),
        ),
        migrations.AlterField(
            model_name='locationspecies',
            name='event_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationspecies', to='whispersapi.EventLocation'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_organizations', to='whispersapi.Organization'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='created_time',
            field=models.TimeField(blank=True, default=datetime.time(15, 8, 30, 329335), null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='event_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whispersapi.EventLocation'),
        ),
        migrations.AlterField(
            model_name='speciesdiagnosis',
            name='location_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speciesdiagnoses', to='whispersapi.LocationSpecies'),
        ),
        migrations.AlterField(
            model_name='speciesdiagnosisorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whispersapi.Organization'),
        ),
        migrations.AlterField(
            model_name='speciesdiagnosisorganization',
            name='species_diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whispersapi.SpeciesDiagnosis'),
        ),
    ]
