# Generated by Django 2.1 on 2018-10-24 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0025_auto_20181023_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='quality_check',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='created_time',
            field=models.TimeField(blank=True, default=datetime.time(21, 41, 39, 589897), null=True),
        ),
    ]
