# Generated by Django 2.1 on 2018-11-27 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0029_auto_20181120_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='created_time',
            field=models.TimeField(blank=True, default=datetime.time(8, 10, 35, 367213), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='speciesdiagnosis',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='speciesdiagnosisorganization',
            unique_together=set(),
        ),
    ]
