# Generated by Django 2.2.4 on 2019-11-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0037_auto_20191031_1551'),
        ('whispersapi', '0037_auto_20191101_1331'),
    ]

    operations = [
    ]
