# Generated by Django 2.2.9 on 2020-01-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0037_auto_20191101_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(help_text='A positive integer value identifying an object'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='object_id',
            field=models.PositiveIntegerField(help_text='A positive integer value identifying an object'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
