# Generated by Django 2.2.4 on 2019-11-26 18:28

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0038_merge_20191101_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(help_text='A positive integer value identifying an object'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='object_id',
            field=models.PositiveIntegerField(help_text='A positive integer value identifying an object'),
        ),
        migrations.CreateModel(
            name='NotificationMessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True)),
                ('modified_date', models.DateField(auto_now=True, help_text='The date this object was last modified on in "YYYY-MM-DD" format', null=True)),
                ('name', models.CharField(help_text='An alphanumeric value of the name of this notification', max_length=128, unique=True)),
                ('message_template', models.TextField(blank=True, help_text='An alphanumeric value of the message of this notification')),
                ('message_variables', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, help_text='An array of alphanumeric values of the variable names of this notification message', size=None)),
                ('created_by', models.ForeignKey(blank=True, help_text='A foreign key integer identifying the user who created the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificationmessagetemplate_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='A foreign key integer identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificationmessagetemplate_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whispers_notificationmessagetemplate',
            },
        ),
        migrations.CreateModel(
            name='HistoricalNotificationMessageTemplate',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True)),
                ('modified_date', models.DateField(blank=True, editable=False, help_text='The date this object was last modified on in "YYYY-MM-DD" format', null=True)),
                ('name', models.CharField(db_index=True, help_text='An alphanumeric value of the name of this notification', max_length=128)),
                ('message_template', models.TextField(blank=True, help_text='An alphanumeric value of the message of this notification')),
                ('message_variables', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, help_text='An array of alphanumeric values of the variable names of this notification message', size=None)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer identifying the user who created the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical notification message template',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
