# Generated by Django 2.2.4 on 2019-12-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0040_auto_20191219_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnotificationmessagetemplate',
            name='message_template',
        ),
        migrations.RemoveField(
            model_name='notificationmessagetemplate',
            name='message_template',
        ),
        migrations.AddField(
            model_name='historicalnotificationmessagetemplate',
            name='long_message_template',
            field=models.TextField(blank=True, help_text='An alphanumeric value of the long message of this notification'),
        ),
        migrations.AddField(
            model_name='historicalnotificationmessagetemplate',
            name='short_message_template',
            field=models.CharField(default='', help_text='An alphanumeric value of the short message of this notification', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationmessagetemplate',
            name='long_message_template',
            field=models.TextField(blank=True, help_text='An alphanumeric value of the long message of this notification'),
        ),
        migrations.AddField(
            model_name='notificationmessagetemplate',
            name='short_message_template',
            field=models.CharField(default='', help_text='An alphanumeric value of the short message of this notification', max_length=128),
            preserve_default=False,
        ),
    ]
