# Generated by Django 2.2.4 on 2020-01-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0041_auto_20191221_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnotification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='historicalnotificationmessagetemplate',
            name='long_message_template',
        ),
        migrations.RemoveField(
            model_name='historicalnotificationmessagetemplate',
            name='short_message_template',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notificationmessagetemplate',
            name='long_message_template',
        ),
        migrations.RemoveField(
            model_name='notificationmessagetemplate',
            name='short_message_template',
        ),
        migrations.AddField(
            model_name='historicalnotification',
            name='body',
            field=models.TextField(blank=True, help_text='An alphanumeric value of the message body of this notification'),
        ),
        migrations.AddField(
            model_name='historicalnotification',
            name='subject',
            field=models.CharField(default='', help_text='An alphanumeric value of the subject of this notification', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalnotificationmessagetemplate',
            name='body_template',
            field=models.TextField(blank=True, help_text='An alphanumeric value of the message body of this notification'),
        ),
        migrations.AddField(
            model_name='historicalnotificationmessagetemplate',
            name='subject_template',
            field=models.CharField(default='', help_text='An alphanumeric value of the subject of this notification', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True, help_text='An alphanumeric value of the message body of this notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(default='', help_text='An alphanumeric value of the subject of this notification', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationmessagetemplate',
            name='body_template',
            field=models.TextField(blank=True, help_text='An alphanumeric value of the message body of this notification'),
        ),
        migrations.AddField(
            model_name='notificationmessagetemplate',
            name='subject_template',
            field=models.CharField(default='', help_text='An alphanumeric value of the subject of this notification', max_length=128),
            preserve_default=False,
        ),
    ]
