# Generated by Django 2.2.9 on 2020-02-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0048_auto_20200207_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnotificationcuepreference',
            name='create_when_modified',
            field=models.BooleanField(default=False, help_text='A boolean value indicating if a notification should be created when a record is modified'),
        ),
        migrations.AlterField(
            model_name='historicalnotificationcuepreference',
            name='create_when_new',
            field=models.BooleanField(default=False, help_text='A boolean value indicating if a notification should be created when a record is new'),
        ),
        migrations.AlterField(
            model_name='historicalnotificationcuepreference',
            name='send_email',
            field=models.BooleanField(default=False, help_text='A boolean value indicating if a notification should be sent by email or not'),
        ),
        migrations.AlterField(
            model_name='notificationcuepreference',
            name='create_when_modified',
            field=models.BooleanField(default=False, help_text='A boolean value indicating if a notification should be created when a record is modified'),
        ),
        migrations.AlterField(
            model_name='notificationcuepreference',
            name='create_when_new',
            field=models.BooleanField(default=False, help_text='A boolean value indicating if a notification should be created when a record is new'),
        ),
        migrations.AlterField(
            model_name='notificationcuepreference',
            name='send_email',
            field=models.BooleanField(default=False, help_text='A boolean value indicating if a notification should be sent by email or not'),
        ),
    ]
