# Generated by Django 2.2.9 on 2020-02-28 23:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0049_auto_20200226_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnotificationcuecustom',
            name='event_location_administrative_level_one',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='A JSON object containing the eventlocation administrativelevelone ID data'),
        ),
        migrations.AlterField(
            model_name='historicalnotificationcuecustom',
            name='event_location_land_ownership',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='A JSON object containing the eventlocation land_ownership ID data'),
        ),
        migrations.AlterField(
            model_name='historicalnotificationcuecustom',
            name='species',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='A JSON object containing the species ID data'),
        ),
        migrations.AlterField(
            model_name='historicalnotificationcuecustom',
            name='species_diagnosis_diagnosis',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='A JSON object containing the speciesdiagnosis diagnosis ID data'),
        ),
        migrations.AlterField(
            model_name='notificationcuecustom',
            name='event_location_administrative_level_one',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='A JSON object containing the eventlocation administrativelevelone ID data'),
        ),
        migrations.AlterField(
            model_name='notificationcuecustom',
            name='event_location_land_ownership',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='A JSON object containing the eventlocation land_ownership ID data'),
        ),
        migrations.AlterField(
            model_name='notificationcuecustom',
            name='species',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='A JSON object containing the species ID data'),
        ),
        migrations.AlterField(
            model_name='notificationcuecustom',
            name='species_diagnosis_diagnosis',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='A JSON object containing the speciesdiagnosis diagnosis ID data'),
        ),
    ]
