# Generated by Django 2.2.10 on 2020-03-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0050_auto_20200228_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnotificationcuecustom',
            name='event_affected_count_operator',
            field=models.CharField(blank=True, default='', help_text='A string representing the operator for event affected_count', max_length=3),
        ),
        migrations.AddField(
            model_name='notificationcuecustom',
            name='event_affected_count_operator',
            field=models.CharField(blank=True, default='', help_text='A string representing the operator for event affected_count', max_length=3),
        ),
    ]
