# Generated by Django 2.2.11 on 2020-05-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0039_auto_20200521_1028'),
        ('whispersapi', '0052_auto_20200520_1423'),
    ]

    operations = [
    ]
