# Generated by Django 2.2.13 on 2020-07-19 15:37

from django.db import connection, migrations


# Reset the sequence for whispers_notificationmessagetemplate since the
# sequence is not used when populating the initial set of templates. See
# whispers_notificationmessagetemplate.sql.
def reset_sequence(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
        SELECT
        setval(pg_get_serial_sequence('"whispers_notificationmessagetemplate"','id'),
        coalesce(max("id"), 1), max("id") IS NOT null) FROM
        "whispers_notificationmessagetemplate"
        """)


def add_user_email_verification_notif_msg_template(apps, schema_editor):
    NotificationMessageTemplate = apps.get_model("whispersapi", "NotificationMessageTemplate")
    db_alias = schema_editor.connection.alias
    NotificationMessageTemplate.objects.using(db_alias).create(
        name="User Email Verification",
        subject_template="Please verify the email address of your WHISPers account",
        body_template="""
<p>
Hello {first_name} {last_name},
</p>

<p>
Thank you very much for your interest in the Wildlife Health Information
Sharing Partnership (WHISPers). You (or someone entering your email address)
requested a WHISPers account. You must verify your email address before your
account can be activated. Please verify your email address by clicking the
link below:
</p>

<p>
<a href="{verification_link}">Verification Link</a>
</p>

<p>
or if that link isn't clickable, copy and paste the following URL into a web
browser:
</p>

<p>
{verification_link}
</p>

<p>
If you did not request a WHISPers account, please disregard this email.
</p>

<p>Thanks again!</p>
        """,
        message_variables=["first_name", "last_name", "verification_link"],
        created_by_id=1,
        modified_by_id=1
    )


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0053_merge_20200521_1119'),
    ]

    operations = [
        migrations.RunPython(reset_sequence, migrations.RunPython.noop),
        migrations.RunPython(add_user_email_verification_notif_msg_template, migrations.RunPython.noop)
    ]
