# Generated by Django 2.2.24 on 2022-07-13 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0057_auto_20210210_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnotification',
            name='template',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the source message template', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='whispersapi.NotificationMessageTemplate'),
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(default=19, help_text='A foreign key integer value identifying the source message template', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='whispersapi.NotificationMessageTemplate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrativeleveltwo',
            name='centroid_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='A fixed-precision decimal number value identifying the latitude for this administrative level two', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='administrativeleveltwo',
            name='centroid_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='A fixed-precision decimal number value identifying the longitude for this administrative level two', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='eventcontact',
            name='contact',
            field=models.ForeignKey(help_text='A foreign key integer value identifying a contact', on_delete=django.db.models.deletion.CASCADE, to='whispersapi.Contact'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='A fixed-precision decimal number value identifying the latitude for this event location', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='A fixed-precision decimal number value identifying the longitude for this event location', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='historicaladministrativeleveltwo',
            name='centroid_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='A fixed-precision decimal number value identifying the latitude for this administrative level two', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='historicaladministrativeleveltwo',
            name='centroid_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='A fixed-precision decimal number value identifying the longitude for this administrative level two', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='historicaleventcontact',
            name='contact',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying a contact', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='whispersapi.Contact'),
        ),
        migrations.AlterField(
            model_name='historicaleventlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='A fixed-precision decimal number value identifying the latitude for this event location', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='historicaleventlocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='A fixed-precision decimal number value identifying the longitude for this event location', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsearch',
            name='count',
            field=models.IntegerField(default=0, help_text='An integer value identifying the count of searches'),
        ),
        migrations.AlterField(
            model_name='search',
            name='count',
            field=models.IntegerField(default=0, help_text='An integer value identifying the count of searches'),
        ),
        migrations.AlterField(
            model_name='speciesdiagnosis',
            name='organizations',
            field=models.ManyToManyField(help_text='A many to many releationship of organizations based on a foreign key integer value identifying an organization', related_name='speciesdiagnoses', through='whispersapi.SpeciesDiagnosisOrganization', to='whispersapi.Organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='circles',
            field=models.ManyToManyField(help_text='A many to many releationship of circles based on a foreign key integer value identifying a circle', related_name='users', through='whispersapi.CircleUser', to='whispersapi.Circle'),
        ),
    ]
