# Generated by Django 2.2.24 on 2023-05-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersapi', '0058_auto_20220713_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='active',
            field=models.BooleanField(default=True, help_text='A boolean value indication if an organization is active or not'),
        ),
        migrations.AddField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=True, help_text='A boolean value indication if an organization is active or not'),
        ),
    ]
