# Generated by Django 2.0 on 2018-06-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0002_auto_20180608_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.ForeignKey(default=1, on_delete='events', to='whispersservices.EventStatus'),
        ),
    ]
