# Generated by Django 2.0 on 2018-07-25 15:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0002_auto_20180724_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesDiagnosisOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='speciesdiagnosisorganization_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='speciesdiagnosisorganization_modifier', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whispersservices.Organization')),
            ],
            options={
                'db_table': 'whispers_speciesdiagnosisorganization',
            },
        ),
        migrations.RemoveField(
            model_name='speciesdiagnosis',
            name='organization',
        ),
        migrations.AddField(
            model_name='eventorganization',
            name='priority',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='speciesdiagnosisorganization',
            name='species_diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whispersservices.SpeciesDiagnosis'),
        ),
        migrations.AddField(
            model_name='speciesdiagnosis',
            name='organizations',
            field=models.ManyToManyField(related_name='speciesdiagnoses', through='whispersservices.SpeciesDiagnosisOrganization', to='whispersservices.Organization'),
        ),
    ]
