# Generated by Django 2.0 on 2018-07-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0003_auto_20180725_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='eventlocation',
            unique_together=set(),
        ),
    ]
