# Generated by Django 2.0 on 2018-06-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0003_auto_20180611_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='legal_status',
            field=models.ForeignKey(default=1, on_delete='events', to='whispersservices.LegalStatus'),
        ),
    ]
