# Generated by Django 2.0 on 2018-04-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0003_auto_20180406_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventabstract',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
