# Generated by Django 2.0 on 2018-06-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0004_auto_20180611_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='affiliation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='quality_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.TextField(blank=True, default=''),
        ),
    ]
