# Generated by Django 2.0 on 2018-04-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0005_group_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='parent_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_organizations', to='whispersservices.Organization'),
        ),
    ]
