# Generated by Django 2.0 on 2018-08-20 20:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0007_auto_20180802_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatEventDetails',
            fields=[
                ('event_id', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('event_reference', models.CharField(max_length=128)),
                ('event_type', models.CharField(max_length=128)),
                ('complete', models.CharField(max_length=128)),
                ('organization', models.CharField(max_length=512)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('affected_count', models.IntegerField()),
                ('event_diagnosis', models.CharField(max_length=512)),
                ('location_id', models.IntegerField()),
                ('location_priority', models.IntegerField()),
                ('county', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('nation', models.CharField(max_length=128)),
                ('location_start', models.DateField()),
                ('location_end', models.DateField()),
                ('location_species_id', models.IntegerField()),
                ('species_priority', models.IntegerField()),
                ('species_name', models.CharField(max_length=128)),
                ('population', models.IntegerField()),
                ('sick', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('estimated_sick', models.IntegerField()),
                ('estimated_dead', models.IntegerField()),
                ('captive', models.CharField(max_length=128)),
                ('age_bias', models.CharField(max_length=128)),
                ('sex_bias', models.CharField(max_length=128)),
                ('species_diagnosis_id', models.IntegerField()),
                ('species_diagnosis_priority', models.IntegerField()),
                ('speciesdx', models.CharField(max_length=128)),
                ('causal', models.CharField(max_length=128)),
                ('confirmed', models.BooleanField()),
                ('number_tested', models.IntegerField()),
                ('number_positive', models.IntegerField()),
                ('row_num', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'flat_event_details',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='search',
            name='owner',
        ),
        migrations.AddField(
            model_name='search',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='search',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
