# Generated by Django 2.0 on 2018-04-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0007_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='active_key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_status',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
