# Generated by Django 2.0 on 2018-04-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0009_auto_20180416_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'searches'},
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='search',
            table='whispers_search',
        ),
    ]
