# Generated by Django 2.0 on 2018-05-24 16:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whispersservices', '0010_auto_20180416_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLocationContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whispersservices.Contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventlocationcontact_creator', to=settings.AUTH_USER_MODEL)),
                ('event_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whispersservices.EventLocation')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventlocationcontact_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whispers_eventlocationcontact',
            },
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='contacts',
            field=models.ManyToManyField(related_name='eventlocationcontacts', through='whispersservices.EventLocationContact', to='whispersservices.Contact'),
        ),
    ]
