# Generated by Django 2.0 on 2018-09-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0011_organization_laboratory'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='gnis_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='gnis_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
