# Generated by Django 2.0 on 2018-04-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0011_auto_20180418_1315_squashed_0013_auto_20180418_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
