# Generated by Django 2.0 on 2018-05-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0012_auto_20180424_1644'),
        ('whispersservices', '0011_auto_20180524_0916'),
    ]

    operations = [
    ]
