# Generated by Django 2.1 on 2018-10-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0014_auto_20181001_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcase',
            name='case',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
