# Generated by Django 2.0 on 2018-05-25 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0015_auto_20180525_1043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='county',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='county',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='county',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='county',
            name='state',
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.RemoveField(
            model_name='state',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='state',
            name='modified_by',
        ),
        migrations.RenameField(
            model_name='administrativelevellocality',
            old_name='admin_level_one',
            new_name='admin_level_one_name',
        ),
        migrations.RenameField(
            model_name='administrativelevellocality',
            old_name='admin_level_two',
            new_name='admin_level_two_name',
        ),
        migrations.RemoveField(
            model_name='eventlocation',
            name='county',
        ),
        migrations.RemoveField(
            model_name='eventlocation',
            name='state',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='state',
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='administrative_level_one',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='eventlocations', to='whispersservices.AdministrativeLevelOne'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='administrative_level_two',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='eventlocations', to='whispersservices.AdministrativeLevelTwo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='administrative_level_one',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='whispersservices.AdministrativeLevelOne'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrativelevelone',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrativelevelones', to='whispersservices.Country'),
        ),
        migrations.AlterField(
            model_name='administrativeleveltwo',
            name='administrative_level_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrativeleveltwos', to='whispersservices.AdministrativeLevelOne'),
        ),
        migrations.DeleteModel(
            name='County',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
