# Generated by Django 2.1 on 2018-10-12 03:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0018_auto_20181011_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimensubmissionrequest',
            name='event_location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='whispersservices.EventLocation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specimensubmissionrequest',
            name='request_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 11, 22, 2, 3, 652816), null=True),
        ),
    ]
