# Generated by Django 2.0 on 2018-06-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0018_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
