# Generated by Django 2.0 on 2018-06-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0019_search_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='epi_staff',
        ),
        migrations.AddField(
            model_name='event',
            name='staff',
            field=models.ForeignKey(null=True, on_delete='events', to='whispersservices.Staff'),
        ),
    ]
