# Generated by Django 2.1 on 2018-10-12 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0019_auto_20181011_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimensubmissionrequest',
            name='request_datetime',
        ),
        migrations.AddField(
            model_name='specimensubmissionrequest',
            name='created_time',
            field=models.TimeField(blank=True, default=datetime.time(15, 10, 59, 241354), null=True),
        ),
    ]
