# Generated by Django 2.1 on 2018-10-12 20:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0020_auto_20181012_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('created_time', models.TimeField(blank=True, default=datetime.time(15, 23, 39, 49643), null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicerequest_creator', to=settings.AUTH_USER_MODEL)),
                ('event_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whispersservices.EventLocation')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicerequest_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whispers_servicerequest',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicerequestresponse_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicerequestresponse_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whispers_servicerequestresponse',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicerequesttype_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicerequesttype_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whispers_servicerequesttype',
            },
        ),
        migrations.RemoveField(
            model_name='specimensubmissionrequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='specimensubmissionrequest',
            name='event_location',
        ),
        migrations.RemoveField(
            model_name='specimensubmissionrequest',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='specimensubmissionrequest',
            name='request_response',
        ),
        migrations.RemoveField(
            model_name='specimensubmissionrequest',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='specimensubmissionrequest',
            name='response_by',
        ),
        migrations.RemoveField(
            model_name='specimensubmissionrequestresponse',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='specimensubmissionrequestresponse',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='specimensubmissionrequesttype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='specimensubmissionrequesttype',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='SpecimenSubmissionRequest',
        ),
        migrations.DeleteModel(
            name='SpecimenSubmissionRequestResponse',
        ),
        migrations.DeleteModel(
            name='SpecimenSubmissionRequestType',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicerequests', to='whispersservices.ServiceRequestResponse'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whispersservices.ServiceRequestType'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='response_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicerequests_responder', to=settings.AUTH_USER_MODEL),
        ),
    ]
