# Generated by Django 2.0 on 2018-06-08 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0020_auto_20180601_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='owner_organization',
        ),
        migrations.AlterField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='whispersservices.Organization'),
        ),
    ]
