# Generated by Django 2.0 on 2018-06-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0021_auto_20180608_0944'),
        ('whispersservices', '0022_comment_comment_type'),
    ]

    operations = [
    ]
