# Generated by Django 2.1 on 2018-10-19 19:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0023_auto_20181018_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='event_location',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicerequests', to='whispersservices.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='created_time',
            field=models.TimeField(blank=True, default=datetime.time(14, 11, 17, 251038), null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicerequests', to='whispersservices.ServiceRequestType'),
        ),
    ]
