# Generated by Django 2.0 on 2018-06-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0024_auto_20180608_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.TextField(blank=True, default=''),
        ),
    ]
