# Generated by Django 2.1 on 2018-10-24 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0026_auto_20181023_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='quality_check',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='created_time',
            field=models.TimeField(blank=True, default=datetime.time(21, 41, 50, 265875), null=True),
        ),
    ]
