# Generated by Django 2.1 on 2018-11-21 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0028_auto_20181025_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='created_time',
            field=models.TimeField(blank=True, default=datetime.time(18, 16, 57, 814311), null=True),
        ),
    ]
