# Generated by Django 2.1.3 on 2018-12-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0031_auto_20181129_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativelevellocality',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicaladministrativelevellocality',
            name='name',
        ),
        migrations.AlterField(
            model_name='contact',
            name='affiliation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
