# Generated by Django 2.2.11 on 2020-05-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0038_auto_20200123_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='active',
            field=models.BooleanField(default=True, help_text='A boolean value indication if a contact is active or not'),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='active',
            field=models.BooleanField(default=True, help_text='A boolean value indication if a contact is active or not'),
        ),
        migrations.AlterField(
            model_name='historicalstaff',
            name='active',
            field=models.BooleanField(default=False, help_text='A boolean value indication if a staff member is active or not'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='active',
            field=models.BooleanField(default=False, help_text='A boolean value indication if a staff member is active or not'),
        ),
    ]
