# Generated by Django 2.2.9 on 2020-01-19 21:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0042_auto_20200109_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUserChangeRequest',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True)),
                ('modified_date', models.DateField(blank=True, editable=False, help_text='The date this object was last modified on in "YYYY-MM-DD" format', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer identifying the user who created the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization_requested', models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying an organization requested for this user change request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='whispersservices.Organization')),
            ],
            options={
                'verbose_name': 'historical user change request',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UserChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True)),
                ('modified_date', models.DateField(auto_now=True, help_text='The date this object was last modified on in "YYYY-MM-DD" format', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='A foreign key integer identifying the user who created the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userchangerequest_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='A foreign key integer identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userchangerequest_modifier', to=settings.AUTH_USER_MODEL)),
                ('organization_requested', models.ForeignKey(help_text='A foreign key integer value identifying an organization requested for this user change request', on_delete=django.db.models.deletion.PROTECT, related_name='userchangerequests', to='whispersservices.Organization')),
            ],
            options={
                'db_table': 'whispers_userchangerequest',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserChangeRequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True)),
                ('modified_date', models.DateField(auto_now=True, help_text='The date this object was last modified on in "YYYY-MM-DD" format', null=True)),
                ('name', models.CharField(help_text='An alphanumeric value of the name of this object', max_length=128, unique=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='A foreign key integer identifying the user who created the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userchangerequestresponse_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='A foreign key integer identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userchangerequestresponse_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whispers_userchangerequestresponse',
                'ordering': ['id'],
            },
        ),
        migrations.RenameModel(
            old_name='HistoricalRoleChangeRequestResponse',
            new_name='HistoricalUserChangeRequestResponse',
        ),
        migrations.RemoveField(
            model_name='rolechangerequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rolechangerequest',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='rolechangerequest',
            name='request_response',
        ),
        migrations.RemoveField(
            model_name='rolechangerequest',
            name='requestor',
        ),
        migrations.RemoveField(
            model_name='rolechangerequest',
            name='response_by',
        ),
        migrations.RemoveField(
            model_name='rolechangerequest',
            name='role_requested',
        ),
        migrations.RemoveField(
            model_name='rolechangerequestresponse',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rolechangerequestresponse',
            name='modified_by',
        ),
        migrations.AlterModelOptions(
            name='historicaluserchangerequestresponse',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical user change request response'},
        ),
        migrations.AlterModelOptions(
            name='notificationcuestandard',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='notificationcuestandard',
            name='notification_cue_preference',
            field=models.OneToOneField(help_text='A foreign key integer value identifying a notificationcuepreference', on_delete=django.db.models.deletion.CASCADE, related_name='notificationcuestandard', to='whispersservices.NotificationCuePreference'),
        ),
        migrations.DeleteModel(
            name='HistoricalRoleChangeRequest',
        ),
        migrations.DeleteModel(
            name='RoleChangeRequest',
        ),
        migrations.DeleteModel(
            name='RoleChangeRequestResponse',
        ),
        migrations.AddField(
            model_name='userchangerequest',
            name='request_response',
            field=models.ForeignKey(default=3, help_text='A foreign key integer value identifying a response to this request', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userchangerequests', to='whispersservices.UserChangeRequestResponse'),
        ),
        migrations.AddField(
            model_name='userchangerequest',
            name='requestor',
            field=models.ForeignKey(help_text='A foreign key integer value identifying a user', on_delete=django.db.models.deletion.CASCADE, related_name='userchangerequests_requestor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userchangerequest',
            name='response_by',
            field=models.ForeignKey(blank=True, help_text='A foreign key integer value identifying the responding user to this request', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userchangerequests_responder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userchangerequest',
            name='role_requested',
            field=models.ForeignKey(help_text='A foreign key integer value identifying a role requested for this user change request', on_delete=django.db.models.deletion.PROTECT, related_name='userchangerequests', to='whispersservices.Role'),
        ),
        migrations.AddField(
            model_name='historicaluserchangerequest',
            name='request_response',
            field=models.ForeignKey(blank=True, db_constraint=False, default=3, help_text='A foreign key integer value identifying a response to this request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='whispersservices.UserChangeRequestResponse'),
        ),
        migrations.AddField(
            model_name='historicaluserchangerequest',
            name='requestor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying a user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaluserchangerequest',
            name='response_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying the responding user to this request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaluserchangerequest',
            name='role_requested',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer value identifying a role requested for this user change request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='whispersservices.Role'),
        ),
    ]
