# Generated by Django 2.2.9 on 2020-01-22 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0043_auto_20200119_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluserchangerequest',
            old_name='requestor',
            new_name='requester',
        ),
        migrations.RemoveField(
            model_name='userchangerequest',
            name='requestor',
        ),
        migrations.AddField(
            model_name='userchangerequest',
            name='requester',
            field=models.ForeignKey(default=1, help_text='A foreign key integer value identifying a user', on_delete=django.db.models.deletion.CASCADE, related_name='userchangerequests_requester', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
