# Generated by Django 2.2.9 on 2020-01-24 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0045_auto_20200123_1432'),
        ('whispersservices', '0038_auto_20200123_1441'),
    ]

    operations = [
    ]
