# Generated by Django 2.2.9 on 2020-02-04 17:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0046_merge_20200123_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalConfiguration',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True)),
                ('modified_date', models.DateField(blank=True, editable=False, help_text='The date this object was last modified on in "YYYY-MM-DD" format', null=True)),
                ('name', models.CharField(db_index=True, help_text='An alphanumeric value of the name of this object', max_length=128)),
                ('value', models.TextField(blank=True, default='', help_text='An alphanumeric value of the value paired to the name for this configuration')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer identifying the user who created the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, help_text='A foreign key integer identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical configuration',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='The date this object was created in "YYYY-MM-DD" format', null=True)),
                ('modified_date', models.DateField(auto_now=True, help_text='The date this object was last modified on in "YYYY-MM-DD" format', null=True)),
                ('name', models.CharField(help_text='An alphanumeric value of the name of this object', max_length=128, unique=True)),
                ('value', models.TextField(blank=True, default='', help_text='An alphanumeric value of the value paired to the name for this configuration')),
                ('created_by', models.ForeignKey(blank=True, help_text='A foreign key integer identifying the user who created the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='A foreign key integer identifying the user who last modified the object', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuration_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whispers_configuration',
                'ordering': ['id'],
            },
        ),
    ]
