# Generated by Django 2.2.9 on 2020-02-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0047_configuration_historicalconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnotificationcuecustom',
            name='event',
            field=models.IntegerField(help_text='An integer representing an event ID', null=True),
        ),
        migrations.AlterField(
            model_name='historicalnotificationcuecustom',
            name='event_affected_count',
            field=models.IntegerField(help_text='An integer representing the event affected_count', null=True),
        ),
        migrations.AlterField(
            model_name='notificationcuecustom',
            name='event',
            field=models.IntegerField(help_text='An integer representing an event ID', null=True),
        ),
        migrations.AlterField(
            model_name='notificationcuecustom',
            name='event_affected_count',
            field=models.IntegerField(help_text='An integer representing the event affected_count', null=True),
        ),
    ]
