# Generated by Django 2.2.11 on 2020-05-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0051_auto_20200303_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-id']},
        ),
    ]
