# Generated by Django 2.2.13 on 2020-07-20 12:58

from django.db import migrations, models


def populate_email_verified_for_existing_users(apps, schema_editor):
    """For all existing users, default email_verified to True."""
    User = apps.get_model("whispersservices", "User")
    db_alias = schema_editor.connection.alias
    all_users = User.objects.using(db_alias).all()
    for user in all_users:
        user.email_verified = True
    User.objects.bulk_update(all_users, ['email_verified'])


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0054_auto_20200719_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='A boolean value indicating if the user has verified their email address or not'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='A boolean value indicating if the user has verified their email address or not'),
        ),
        migrations.RunPython(populate_email_verified_for_existing_users)
    ]
