# Generated by Django 2.2.13 on 2020-08-10 18:39

from django.db import migrations


def add_password_reset_notif_msg_template(apps, schema_editor):
    NotificationMessageTemplate = apps.get_model("whispersservices", "NotificationMessageTemplate")
    db_alias = schema_editor.connection.alias
    NotificationMessageTemplate.objects.using(db_alias).create(
        name="Password Reset",
        subject_template="Password reset for WHISPers",
        body_template="""
<p>
Hello {first_name} {last_name},
</p>

<p>
Someone requested a password reset for your WHISPers user account. If that
was you, please click the following link to reset your password:
</p>

<p>
<a href="{password_reset_link}">Reset Password</a>
</p>

<p>
or if that link isn't clickable, copy and paste the following URL into a web
browser:
</p>

<p>
{password_reset_link}
</p>

<p>
If you did not request a password reset, please disregard this email.
</p>
        """,
        message_variables=["first_name", "last_name", "password_reset_link"],
        created_by_id=1,
        modified_by_id=1
    )


class Migration(migrations.Migration):

    dependencies = [
        ('whispersservices', '0055_auto_20200720_1258'),
    ]

    operations = [
        migrations.RunPython(add_password_reset_notif_msg_template)
    ]
